### ISSUE TITLE
cannot join cdma network

### ISSUE THREAD

**Issue by mia0x75** [AICP/device_huawei_angler#2]
China Telecomm user, show no SIM card, no service on statusbar, while official 8.1 ROM works

**Comment by LorDClockaN** [comment]
You have the latest vendor, radio and bootloader images? ~~ Flowed from my Pixel XL2 ~~On Mar 10, 2018 05:42, mia0x75 <notifications@github.com> wrote:China Telecomm user, show no SIM card, no service on statusbar, while official 8.1 ROM works

**Comment by mia0x75** [comment]
the vendor is : vendor-angler-OPM3.171019.016.img, download from http://kantjer.com/image/

**Comment by LorDClockaN** [comment]
Radio also from the same image? If yes, then I don't know~~ Flowed from my Pixel XL2 ~~On Mar 11, 2018 00:41, mia0x75 <notifications@github.com> wrote:the vendor is : vendor-angler-OPM3.171019.016.img

**Comment by mia0x75** [comment]
Yes, radio is radio-angler-03.85.img from the same website.

**Comment by mia0x75** [comment]
try to China Unincom, it does work either. (TD-LTE FDD-LTE)

**Comment by mia0x75** [comment]
1. re-flash official ROM
2. flash recovery
3. use latest 0316 AICP

it works now.
